# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-26 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OMXOrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customID', models.CharField(max_length=45)),
                ('orderNumber', models.CharField(max_length=15)),
                ('customerID', models.IntegerField()),
                ('orderDate', models.DateField()),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('itemCode', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=70)),
                ('vendorName', models.CharField(max_length=30)),
                ('dropShipCOG', models.FloatField()),
                ('qty', models.IntegerField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='QBImportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customID', models.CharField(max_length=45)),
                ('enterWeek', models.CharField(max_length=45)),
                ('paymentDate', models.DateField(max_length=45)),
                ('vendorName', models.CharField(max_length=45)),
                ('invocieTotal', models.FloatField()),
                ('dropShipFee', models.FloatField()),
                ('shippingFee', models.FloatField()),
                ('omxPO', models.IntegerField()),
                ('omxTotal', models.FloatField()),
                ('totalDifference', models.FloatField()),
                ('discrepancy', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='VendorNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qbVendorName', models.CharField(max_length=150)),
                ('omxVendorName', models.CharField(max_length=150)),
            ],
        ),
    ]
