# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-26 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbreport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omxorderhistory',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='omxorderhistory',
            name='firstName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='omxorderhistory',
            name='lastName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='omxorderhistory',
            name='vendorName',
            field=models.CharField(max_length=600),
        ),
    ]
