# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-26 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbreport', '0002_auto_20171226_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omxorderhistory',
            name='customerID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='omxorderhistory',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='omxorderhistory',
            name='dropShipCOG',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='omxorderhistory',
            name='firstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='omxorderhistory',
            name='itemCode',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='omxorderhistory',
            name='lastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='omxorderhistory',
            name='orderDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='omxorderhistory',
            name='orderNumber',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='omxorderhistory',
            name='qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='omxorderhistory',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='omxorderhistory',
            name='vendorName',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
