# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-28 17:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qbreport', '0003_auto_20171226_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('orderReport', models.FileField(upload_to='qbreports/uploads/')),
                ('uploadDate', models.DateTimeField(default=datetime.datetime(2017, 12, 28, 17, 2, 52, 571981, tzinfo=utc))),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Uploaded Files',
            },
        ),
        migrations.AlterModelOptions(
            name='omxorderhistory',
            options={'verbose_name_plural': 'OMX Order History'},
        ),
        migrations.AlterModelOptions(
            name='vendornames',
            options={'verbose_name_plural': 'Vendor Names'},
        ),
        migrations.AlterField(
            model_name='qbimportfile',
            name='paymentDate',
            field=models.DateField(),
        ),
    ]
