# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-31 04:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qbreport', '0005_auto_20171230_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qbimportfile',
            name='invoiceDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='uploadDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 31, 4, 49, 9, 928737, tzinfo=utc)),
        ),
    ]
