# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-31 05:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qbreport', '0009_auto_20171230_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='uploadDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 31, 5, 17, 6, 45399, tzinfo=utc)),
        ),
    ]
