# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-31 05:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qbreport', '0010_auto_20171230_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qbimportfile',
            name='invoiceNumber',
            field=models.IntegerField(default=123),
        ),
        migrations.AlterField(
            model_name='qbimportfile',
            name='poNumb',
            field=models.IntegerField(default=123),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='uploadDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 31, 5, 18, 30, 424573, tzinfo=utc)),
        ),
    ]
