# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-31 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qbreport', '0012_auto_20171230_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='uploadDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
