# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-03 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbreport', '0013_auto_20171230_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='formatedFile',
            field=models.FileField(default='qbreports/uploads/test.xlsx', upload_to='qbreports/uploads/'),
        ),
    ]
