# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-04 19:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbreport', '0016_auto_20180104_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qbimportfile',
            name='invoiceNumber',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d\\d\\d\\d\\d\\d-\\d\\d$')]),
        ),
    ]
