# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-13 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qbreport', '0017_auto_20180104_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qbimportfile',
            name='enterWeek',
        ),
        migrations.RemoveField(
            model_name='qbimportfile',
            name='paymentDate',
        ),
    ]
