# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-13 21:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbreport', '0018_auto_20180113_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='qbimportfile',
            name='memo',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='qbimportfile',
            name='discrepancy',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='qbimportfile',
            name='dropShipFee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qbimportfile',
            name='invocieTotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qbimportfile',
            name='omxPO',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qbimportfile',
            name='omxTotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qbimportfile',
            name='poNumb',
            field=models.IntegerField(null=True, validators=[django.core.validators.RegexValidator('^\\d\\d\\d\\d\\d\\d-\\d\\d$')]),
        ),
        migrations.AlterField(
            model_name='qbimportfile',
            name='shippingFee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qbimportfile',
            name='totalDifference',
            field=models.FloatField(default=None),
        ),
    ]
