# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-17 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbreport', '0020_auto_20180113_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='qbimportfile',
            name='notes',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
