# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-27 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbreport', '0022_auto_20180124_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedToAddVendorToDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verndorname', models.CharField(blank=True, max_length=45, null=True, unique=True)),
            ],
        ),
    ]
