# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-20 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbreport', '0023_needtoaddvendortodatabase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qbimportfile',
            name='memo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
