# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-08 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repricing', '0003_delete_repricingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='repricingomxdata',
            name='bfdItemCode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
