# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-06 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetailBloom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('total_rows', models.IntegerField(null=True)),
                ('uploadDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_location', models.CharField(max_length=100)),
                ('retailbloom_Report', models.FileField(upload_to='retailbloom\\uploads\\')),
            ],
            options={
                'verbose_name_plural': 'Retail Bloom Data',
            },
        ),
    ]
