# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-16 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonbulletpoints', '0002_auto_20180216_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetail',
            name='yahooID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
