# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-16 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonbulletpoints', '0003_auto_20180216_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetail',
            name='description',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='itemCode',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='itemName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
