# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-16 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonbulletpoints', '0004_auto_20180216_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetail',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
